import Head from "next/head";
import About from "../../components/About";
import Benefits from "../../components/Benefits";
import Hero from "../../components/Hero";
import Navbar from "../../components/Navbar";

export default function Portfolio() {
  return (
    <main>
      <Head>
        <title>Portfolio - The Coding Montana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Benefits />
    </main>
  );
}
